### ISSUE TITLE
Over reliance on evaluate_model

### ISSUE THREAD

**Issue by lucianopaz** [pymc-devs/pymc4#167]
Currently, `sample`, `sample_prior_predictive` and `sample_posterior_predictive` all use a first call to some variant of `evaluate_model` just to get some meta information of the model:
* Identify the variables that define the sampling state, along with their shape (in `sample`)
* Identify the distribution shape and the observed variables (in both forward sampling methods)
* To help with auto batching (in both forward sampling methods)

All of these will lead to problems for models that cannot generate samples from the prior. For example, models with `Flat` priors (see [this pymc3 issue](https://github.com/pymc-devs/pymc3/issues/3294))

I think that the solution to this problem is to introduce some purely symbolic model parser to get the metadata we need. I think that we should do this with [symbolic-pymc](https://github.com/pymc-devs/symbolic-pymc)

**Comment by lucianopaz** [comment]
Pinging @brandonwillard over this.

If we don't go symbolic, the alternatives I can think of are:

1. making a special executor that evaluates the model but instead of calling `sample` on distributions, it returns an array of Nan's with the appropriate tensor shape.
2. Doing something that parses the AST to extract the metadata.

I think that option 1 would be easy to implement, but I think that pymc4 could benefit much more by starting to integrate the symbolic-pymc manipulations @brandonwillard is working on.

**Comment by brandonwillard** [comment]
We could almost certainly extract all the necessary information from TFP-generated graphs (which would be much easier with PyMC4/TFP name correspondence, if that's working now).

Otherwise, we could build and use `symbolic-pymc` meta graphs from the start.  If you don't use logic variables with them, they're basically just low-level, generic delayed TF graphs&mdash;that are easily converted to real TF graphs with `MetaSymbol.reify`.

I'll need to know more about the shape-related needs, because there may be TF-only difficulties with obtaining shape information for a specific node in the exact  form/way we need it.

**Comment by lucianopaz** [comment]
@brandonwillard, how would we bypass eager mode to get the tf graph? Would we need a `function` decorator? That would still have to rely on `evaluate_model` to trace the function and generate the graph, right?

As for the shape issues, tfp has the three semantic shapes: sample, batch and event. Currently, all three methods always leave
`sample_shape=()` and use `tf.vectorized_map` to draw many samples in parallel. Inside the model, batch and event shapes don't need to be disambiguated because the `log_prob` given to `inference.sampling.sample` automatically reduces all the batch shape axes, and relies on `tf.vectorized_map` to auto batch across multiple chains. So what we need effectively is to be able to infer the default `batch_shape + event_shape` of all distributions, and the `shape` of `Potential`s and `Deterministic`s.

I am planning on adding some way for users to opt out of auto batching, and in that case, they should explicitly deal with all three semantic shapes by themselves (i.e. batch and event shapes will matter for `log_prob`, and `sample_shapes` of draws from one distribution will be interpreted as batches for a distribution that conditionally depends on the previous one).

**Comment by brandonwillard** [comment]
> @brandonwillard, how would we bypass eager mode to get the tf graph? Would we need a `function` decorator? That would still have to rely on `evaluate_model` to trace the function and generate the graph, right?

We can already get the graph information from the results of `evaluate_model`; see the example [here](https://pymc-devs.github.io/symbolic-pymc/tensorflow-radon-example.html#logp-func), where `evaluate_model` is called implicitly via `pm.inference.sampling.build_logp_function` and the model's graph is extracted as a `FuncGraph` from the generated `tf.function` used therein.

In this case, we don't need to _numerically_ evaluate the log-likelihood graph generated by `evaluate_model` (within&mdash;and "captured" by&mdash;the `tf.function` of `pm.inference.sampling.build_logp_function`), of course.


> As for the shape issues, tfp has the three semantic shapes: sample, batch and event. Currently, all three methods always leave
> `sample_shape=()` and use `tf.vectorized_map` to draw many samples in parallel. Inside the model, batch and event shapes don't need to be disambiguated because the `log_prob` given to `inference.sampling.sample` automatically reduces all the batch shape axes, and relies on `tf.vectorized_map` to auto batch across multiple chains. So what we need effectively is to be able to infer the default `batch_shape + event_shape` of all distributions, and the `shape` of `Potential`s and `Deterministic`s.

Unfortunately, the approach I just mentioned probably won't yield the batch and event shapes, since those values are most likely already collapsed in exactly the way you described when `evaluate_model_transformed` is called inside the `tf.function` of `pm.inference.sampling.build_logp_function`.

It looks like we would have to gather/track that node-specific information explicitly within PyMC4, which itself would be more than a half-step toward building a model graph.

**Comment by lucianopaz** [comment]
The thing is that there are some models that will raise a `NotImplementedError` inside of `evaluate_model`, making the evaluation fail. For example, any model with a `Flat` or `HalfFlat` prior will fail to generate samples from the prior. However, it should still be possible to `sample` and `sample_posterior_predictive` from them. The problem is that both of those first try to draw a sample from the prior using `evaluate_model` to get the metadata.

If symbolic-pymc also needs `evaluate_model` to succeed, then we will have to use a different approach, like a custom executor.

**Comment by brandonwillard** [comment]
> The thing is that there are some models that will raise a `NotImplementedError` inside of `evaluate_model`, making the evaluation fail. For example, any model with a `Flat` or `HalfFlat` prior will fail to generate samples from the prior.

Is there a PyMC4 example I can look at?  I don't see a reason why we couldn't generate a sample-space graph for almost any model/distribution.

`symbolic-pymc` doesn't actually use or need `evaluate_model`; it's just the most expedient way&mdash;that I know of&mdash;to call TFP's `sample` method on distributions defined within a PyMC4 model.  

`symbolic-pymc` is designed to support conversion to and from **backend graphs** (i.e. Theano and TensorFlow).  

We could just as (or more) easily add direct support for "PyMC4/TFP graphs" (e.g. the distribution classes) and walk those objects without calling `sample`, but that development path leads to an extremely error-prone and&mdash;in principle&mdash;unnecessary back-and-forth between graphs (e.g. the sample-space graphs implied by TFP distributions *and* the TF graphs inside distributions parameters *and* back to TFP distribution objects within those, etc.)  More specifically, in order to use two types of graphs together we would most likely need to duplicate operators and map-out all the operator conversions (e.g. we would need an addition operator for TFP/PyMC4 distributions and that would need a consistent 1:1 mapping with one or more of the TF addition operators).

This is one reason why I'm always fighting for parity with&mdash;and the primacy of&mdash;backend graphs.

**Comment by lucianopaz** [comment]
Oh, it looks like there is no `Flat` distribution in tfp, and we haven't rolled out our own yet. @brandonwillard, I would point you to the [pymc3 issue](https://github.com/pymc-devs/pymc3/issues/3294) that made me think that this would also be a problem for pymc4.
