### ISSUE TITLE
Is there any Data class ?

### ISSUE THREAD

**Issue by hotessy** [pymc-devs/pymc4#251]
Is there any `pm.Data` class available [like in pyMC3](https://docs.pymc.io/api/data.html#module-pymc3.data) ?

**Comment by lucianopaz** [comment]
At the moment there is no `Data` class like what pymc3 has. This is mainly due to the tensorflow 2 design that focuses on functional programming and eager execution instead of symbolic computational graphs, like what theano did. In pymc3, models were objects, and to be able to change the data values of a model that had already been created, we relied on `theano.shared`. Pymc4 will be different because models are essentially functions. We haven't written a notebook with a recommended procedure on how to pass data into a model, but we imagine that we will do it using function arguments. That way, if you want to change the data values between training and testing, you would just have to change the argument values you supplied to the model function.
However, there is no clear roadmap on this topic and we may have to change some design choices to also be able to accommodate `tf.Dataset`.

**Comment by hotessy** [comment]
Thanks for the detailed reply and mentioning possible routes I could take, @lucianopaz.
