### ISSUE TITLE
`sample_prior_predictive` and `sample_posterior_predictive` issues with `use_auto_batching=False`

### ISSUE THREAD

**Issue by dirmeier** [pymc-devs/pymc4#293]
Hi, 

when sampling from the prior predictive with `use_auto_batching=False` setting `sample_shape` doesn't work and always a single draw is returned:

```python
dat = tfd.Normal(loc=1.0, scale=1.0).sample(10)

@pm.model
def model():
    m = yield pm.Normal("mean", loc=0.0, scale=1.0)
    lik = yield pm.Normal("lik", loc=m, scale=1.0, observed=dat)
    return lik

mod = model()
ppc = pm.sample_prior_predictive(mod, sample_shape=10, use_auto_batching=False)
ppc = ppc.prior_predictive
print(ppc["model"])

<xarray.DataArray 'model' (chain: 1, draw: 1)>
array([[-0.6240528]], dtype=float32)
Coordinates:
  * chain    (chain) int64 0
  * draw     (draw) int64 0
``` 

Similar behaviour is true when sampling from the posterior predictive. Am I missing something here? Colab that shows this is [here](https://colab.research.google.com/drive/1EWR6yCjouhsC-AtwyOURqCrPsHGJH_fP?usp=sharing).

Thanks!

Cheers,
Simon

**Comment by lucianopaz** [comment]
@dirmeier, the problem is that you didn't specify that `m` is `conditionally_independent=True`. This isn't properly documented because I never had the time to write an explanatory notebook on how to manually vectorize a model. The closest thing there is at the moment is [this example from the forward sampling functions](https://github.com/pymc-devs/pymc4/blob/master/pymc4/forward_sampling.py#L143-L169)

**Comment by lucianopaz** [comment]
Oh, by the way, of you are interested in fully vectorizing also the `log_prob` calculation, you'll have to also pass `event_stack=observed.shape` to `lik`

**Comment by dirmeier** [comment]
Ah, right! Thanks.
