### ISSUE TITLE
Distribution parameters

### ISSUE THREAD

**Issue by ericmjl** [pymc-devs/pymc4#58]
TFP Normal uses NumPy's `loc` and `scale`.

PyMC3 used `mu` and `sigma` (or alternatively `tau` or `sd`). 

What are our thoughts on parametrization of distributions? Follow TFP only, or provide the alternative parametrizations as well? 

Speaking for myself here, I believe that it's better for UX to keep PyMC3 parametrizations - it means fewer things to change API-wise, for an end-user.

**Comment by eigenfoo** [comment]
Just to note: it looks like PyMC4's API will be quite different from PyMC3's in the first place. E.g. defining a model looks like it happens through a decorator instead of a context manager. So I don't think we should shy away from API changes if they bring benefits in the backend.

That being said though, I did like how PyMC3 had predictable Greek parameters - and TFP's parameter names are fairly unfriendly (e.g. the Beta distribution's `concentration0` and `concentration1`). I'm just concerned that renaming parameters will involve a lot of boilerplate code on our part. Basically I'd like to have Greek parameter names, but I think we should worry about that after we have working, well-tested random variables 😇

**Comment by fonnesbeck** [comment]
I think we should err on the side of consistency with PyMC 3 over TFP, where we have a choice.

**Comment by ericmjl** [comment]
Agreed - if that means creating a few extra lines of code in the codebase per probability distribution, such that migration from PyMC3 to PyMC4 is smoother, I think it's worthwhile for our users (of which we are subsets as well).

**Comment by canyon289** [comment]
IMO the ideal scenario would be being able to copy over pymc3 models with minimal changes

**Comment by ericmjl** [comment]
I like the "model as a function" paradigm, btw - it fits the "generative model" kind of way of thinking, IMO. :smile:

**Comment by twiecki** [comment]
We settled this to use greek symbols like in PyMC3.

**Comment by ericmjl** [comment]
*greek names. Greek unicode symbols would make things super challenging! :smile:
