### ISSUE TITLE
pass RV.sample(*args, **kwargs) to tfp.distribution.sample(*args, **kwargs)

### ISSUE THREAD

**Issue by majidaldo** [pymc-devs/pymc4#96]
https://github.com/pymc-devs/pymc4/blob/1a30106869f57b545bcb67bd9b10d4aff996c233/pymc4/random_variables/random_variable.py#L129

why would you want to limit yourself to only sample once per call?

**Comment by ericmjl** [comment]
Not sure of design choice here. @twiecki and @junpenglao?

**Comment by majidaldo** [comment]
What value is pymc adding anyways to distributions? arithmetic ops?

**Comment by ericmjl** [comment]
In the long-run, a hopefully more user-friendly API than the TFP API. The pm3 API was superb; at least for myself, it's facilitated learning and solving problems, formulating models, and modelling in general.

**Comment by majidaldo** [comment]
tfp distributions methods resemble pm3 RVs. Of course, the magic is in how you put the RVs together.

**Comment by ericmjl** [comment]
> tfp distributions methods resemble pm3 RVs

Yes, the only difference being that TFP has distribution parameterizations that are more programmer-friendly, and less statistician-friendly. 

> Of course, the magic is in how you put the RVs together.

Agreed! Two days ago, was trying to implement a zero-inflated Beta distribution. Colleague and I sorta got it working, probably could be better; pm3's API was superb for doing this.

**Comment by junpenglao** [comment]
> why would you want to limit yourself to only sample once per call?

This is actually the safest choice to avoid incorrect shape broadcasting. Take the model in https://docs.pymc.io/notebooks/hierarchical_partial_pooling.html as an example, if you were to write a sample function for this model in pure TFP, you might put it down as such:
```python
def custom_forward(nmc, n_obs):
  phi = tfd.Uniform(low=a, high=b).sample(nmc)
  kappa_log = tfd.Exponential(rate=tf.cast(1.5, dtype)).sample(nmc)
  thetas = tfd.Beta(concentration1=tf.tile((tf.exp(kappa_log)*phi)[:, None], (1, n_obs)),
                    concentration0=tf.tile((tf.exp(kappa_log)*(1.0-phi))[:, None], (1, n_obs))).sample(nmc)
  y = tfd.Binomial(
      total_count=tf.cast(at_bats, dtype),
      probs=thetas
  ).sample(nmc) <== This wont work as Binomial does not have sample_n yet
  return phi, kappa_log, thetas, y
```

Note the number of MC sample is defined as `nmc`. However, if you run the function like `custom_forward(4, 18)`, you would actually get incorrect (or rather, unintuitive) tensors:
```python
(<tf.Tensor 'Uniform/sample/Reshape:0' shape=(4,) dtype=float64>,
 <tf.Tensor 'Exponential/sample/Reshape:0' shape=(4,) dtype=float64>,
 <tf.Tensor 'Beta/sample/Reshape:0' shape=(4, 4, 18) dtype=float64>,
 <tf.Tensor 'Binomial/sample/Reshape:0' shape=(4, 4, 4, 18) dtype=float64>,
```

More problematic, the result is not the same as when you run:
```python
for i in range(4): 
    ... = custom_forward(1, n_obs)
```
The (stacked) result will have a different but now correct shape:
```python
(<tf.Tensor 'Uniform/sample/Reshape:0' shape=(4,) dtype=float64>,
 <tf.Tensor 'Exponential/sample/Reshape:0' shape=(4,) dtype=float64>,
 <tf.Tensor 'Beta/sample/Reshape:0' shape=(4, 18) dtype=float64>,
 <tf.Tensor 'Binomial/sample/Reshape:0' shape=(4, 18) dtype=float64>,
```
the reason is that where in the context of Bayesian model checking, what you actually want is that the last two RV does not do additional boardcasting. 

So at the end, the safest way is to do `sample()` (or `sample(1)` to make sure you dont end up accidentally broadcasting something). Moreover, `sample()` dont require user to always think about batch shape (which could be tricky or even impossible in some cases).

**Comment by junpenglao** [comment]
> tfp distributions methods resemble pm3 RVs. Of course, the magic is in how you put the RVs together.

TFP distribution does not resemble RV, that's why you need Edward2 inside TFP to actually do that.

**Comment by junpenglao** [comment]
Close for now, but feel free to keep discussing here!

**Comment by ericmjl** [comment]
> TFP distribution does not resemble RV, that's why you need Edward2 inside TFP to actually do that.

Ah yes, @junpenglao is correct! I was not thinking straight when I responded. :smile:

**Comment by ericmjl** [comment]
@junpenglao your code style has become Googlified!

**Comment by junpenglao** [comment]
@ericmjl If you meant the 2 space yep I am guilty as charged...
